# Generated by Django 2.2.2 on 2020-09-18 20:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_api_backend_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_uuid',
            field=models.CharField(default=users.models.uuid_str, max_length=100, unique=True),
        ),
    ]
