# Generated by Django 2.2.2 on 2020-09-19 12:01

from django.db import migrations

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.management import create_permissions

def create_group_and_permission(apps, schema_editor):
    group, created = Group.objects.get_or_create(name='View_Manufacture_and_car')


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permission),
    ]
